databases:
  - name: postgres
    databaseName: recipe_app
    ipAllowlist: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: b30786422ac2cd67714be2f7949896e2
        sync: false
  -type: redis
   name: redis
   ipAllowlist: []
   plan: free
   maxmemoryPolicy: noeviction
